# Generated by Django 3.1.1 on 2020-09-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='offer',
            old_name='price',
            new_name='description',
        ),
    ]
